version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python3 manage.py runserver 127.0.0.1:8000"
    container_name: simplicar
    volumes:
      - .:/simplicar
    ports:
      - "8000:8000"