# Generated by Django 3.1.7 on 2021-04-01 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210401_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.library')),
            ],
        ),
        migrations.DeleteModel(
            name='Leads',
        ),
    ]
