# Generated by Django 3.1.7 on 2021-04-01 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20210401_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='libraries',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='library',
        ),
    ]
