# Generated by Django 3.1.7 on 2021-04-01 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20210401_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.library'),
        ),
    ]
